name: MSVC
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildUbuntu:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: install\setup.bat
    - name: make
      run: cmake --build build/debug

