name: Ubuntu
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildUbuntu:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sh install/setupUbuntu.sh
    - name: make
      run: cmake --build build --parallel

